### ISSUE TITLE
Comparison failure on identical objects, which contain empty arrays

### ISSUE THREAD

**Issue by maxyushchenko** [defrag/NMatcher#5]
### Problem:
When using NMatcher for simple structural comparison of two identical JSON objects, it fails, despite the objects are identical. Sample code:
```
        [Fact]
        public void empty_array_obj()
        {
            var testJson = @"{ ""test"": []}";

            testJson.Should().MatchJson(testJson);
        }
```

Where `MatchJson` is a wrapper around `matcher.MatchJson`.
The error message looks like that: `System.Object[] did not match null at path test.`

### Expected behavior:
Structural comparison produces successful results for identical objects (incl. ones with empty arrays).

**Comment by defrag** [comment]
Resolved by #6.
